config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, except: %i[destroy update edit] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  # before_destroy :check_for_bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true

  # private

  # def check_for_bookmarks
  #   if bookmarks.count > 0
  #     errors.add_to_base("This movie has bookmarks. It can't be deleted.")
  #     false
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/:id/bookmark/new', status: :unprocessable_entity
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    bookmark.destroy
    redirect_to list_path(bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @movies = @list.movies

  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_param)
    if @list.save
      redirect_to @list, notice: 'List was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_param
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Create new bookmark for list <%= @list.name %></h1>
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <% f.error_notification %>
  <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>

<% @lists.each do |list| %>
  <h2>List #<%= list.id %>: <%= list.name %></h2>
<% end %>

app/views/lists/new.html.erb
<h1>Create a new list</h1>
<%= simple_form_for(@list) do |f| %>
  <% f.error_notification %>
  <% f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<p><strong>List ID: </strong><%= @list.id %></p>
<% @movies.each do |movie| %>
  <p><strong>Movie title: </strong><%= movie.title %></p>
  <p><strong>Movie overview: </strong><%= movie.overview %></p>
  <p><strong>Movie rating: </strong><%= movie.rating %></p>
  <%= image_tag(movie.poster_url) %>
  <% @book = movie.bookmarks %>
  <% @book.each do |bookmark| %>
    <p><%= bookmark.comment%> - <%= link_to "remove", bookmark_path(bookmark), data: { turbo_method: :delete } %></p>
  <% end %>
<% end %>